# Write a function to compute 5/0 and use try/except to catch the exceptions

In [0]:
def ComputeException(input_1=None,input_2=None):
  if input_1==None:
    print('Please provide proper value for input_1')
  elif input_2==None:
     print('Please provide proper value for input_2')
  elif input_1==None and input_2==None:
    print('Please provide proper value for input_1 and input_2')
  else:
    try:
      result=input_1/input_2
      print(result)
    except Exception as e:
      #print(dir(e))
      print('The error is {}'.format(e)) 
      #print(e.with_traceback)

  


In [27]:
ComputeException(5,0)

The error is division by zero


# Implement a Python program to generate all sentences where subject is in 

["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].


subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [0]:
def CreateCombination(subject_val=None,verb_val=None,object_val=None):
  if subject_val==None or verb_val==None or object_val==None:
    print('please enter proper values for subject,verb and object')
  else:
    for s in subject_val:
      for v in verb_val:
        for o in object_val:
           print(s,v,o)

In [41]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
CreateCombination(subject_val=subjects,verb_val=verbs,object_val=objects)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [0]:
import numpy as np
def CreateVanderMatrix(input_val=None,N=None):
   val=np.zeros((N,len(input_val)))
   #print(len(input_val))
   for i in range(val.shape[0]):
      for j in range(val.shape[1]):
         val[i,j]=input_val[j]**i
   output_temp=val.T
   print(output_temp[:,::-1])

In [66]:
input_val=[1,2,3,4]
N=5
CreateVanderMatrix(input_val,N)

[[  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]]
